// _Mov_Player1.cpp - Generated by VisualRTXC
// Autor: Thiago Neves Romero
// Autor: Rafael Edurado Wolf de Goes
// UFSCar - Universidade Federal de São Carlos

#include "kcounter.h"
#include "kmutx.h"
#include "ktask.h"
#include "rtxcapi.h"
#include "kproject.h"
#include "objetos.h"
#include "Util.h"

extern circulo bola[5];
extern quadrilatero player1;
extern int qtdBola;
extern int velocidade;

void task__Mov_Player1(void);

void task__Mov_Player1(void)
{
	int indBola=0;
	
	while(1)
	{
		// Bola mais proxima
		for(int i=0;i<qtdBola;i++)
		{
			if(bola[i].v.x<bola[indBola].v.x)
			{
				indBola=i;
			}
		}
		// Subir Player 1
		if(bola[indBola].v.y-bola[indBola].raio<player1.v1.y)
		{
			KS_TestMutxW(M_P1);
			if(player1.v1.y-INC_PLAYER>TOPO)
			{
				player1.v1.y-=INC_PLAYER;
				player1.v2.y-=INC_PLAYER;
			}
			else
			{
				player1.v2.y-=(player1.v1.y-TOPO-1);
				player1.v1.y-=(player1.v1.y-TOPO-1);
			}
			KS_ReleaseMutx(M_P1);
		}
		else
		{
			// Descer Player 1
			if(bola[indBola].v.y+bola[indBola].raio>player1.v2.y)
			{
				KS_TestMutxW(M_P1);
				if(player1.v2.y+INC_PLAYER<INFERIOR)
				{
					player1.v1.y+=INC_PLAYER;
					player1.v2.y+=INC_PLAYER;
				}
				else
				{
					player1.v1.y+=(INFERIOR - player1.v2.y -1);
					player1.v2.y+=(INFERIOR - player1.v2.y -1);
				}
				KS_ReleaseMutx(M_P1);
			}
		}
		KS_SleepTask(SYSTIMER, (TICKS)100-(velocidade*10)/CLKTICK);
	}
}
