// _Player1.cpp - Generated by VisualRTXC
// Autor: Thiago Neves Romero
// Autor: Rafael Edurado Wolf de Goes
// UFSCar - Universidade Federal de São Carlos

#include "kmutx.h"
#include "ktask.h"
#include "rtxcapi.h"
#include "kproject.h"
#include "objetos.h"
#include "graphics.h"

extern quadrilatero player1;

void task__Player1(void);

void task__Player1(void)
{
	KS_TestMutxW(M_P1);
	// Player 1
	player1.v1.x=6;
	player1.v1.y=125;
	player1.v2.x=20;
	player1.v2.y=274;
	player1.filltype=SOLID_FILL;
	player1.fillcolor=RED;
	
	KS_ReleaseMutx(M_P1);
	KS_TerminateTask(SELFTASK);
}
