// _Principal.cpp - Generated by VisualRTXC
// Autor: Thiago Neves Romero
// Autor: Rafael Edurado Wolf de Goes
// UFSCar - Universidade Federal de São Carlos

#include "kcounter.h"
#include "kmutx.h"
#include "ktask.h"
#include "kthread.h"
#include "kpart.h"
#include "rtxcapi.h"
#include "kproject.h"
#include <stdlib.h>
#include <windows.h>
#include "objetos.h"
#include "graphics.h"
#include "Util.h"

// Declaracoes Globais

// Objetos
tabuleiro t;
quadrilatero player1;
quadrilatero player2;
circulo bola[5];

// Variaveis de controle
int indiceBola[5];
extern int qtdBola;
bool quit = false;
extern int velocidade;

// Score
int scoreP1 = 0;
int scoreP2 = 0;

// Declaracoes de tarefas dinamicas
extern const TASKPROP taskprop;
extern void task__Mov_Bola(void);

// Declaracao de flag para finalizar programa
extern volatile int brkflag;


void task__Principal(void);

void task__Principal(void)
{
	// Declaracoes Locais
	int GraphDriver = DETECT,GraphMode = 0;
	
	// _Mov_Bola
	TASK taskBola[5];
	char *pstackBola[5];
	
	PRIORITY taskpri = 5;
	TASKPROP taskprop;
	ksize_t stacksize = 1024;
	
	for(int i=0;i<qtdBola;i++) 
	{
		KS_OpenTask((char *)0, &taskBola[i]);
		pstackBola[i] = (char *)KS_AllocBlk(STKPART);
	
		taskprop.priority = taskpri;
		taskprop.stackbase = pstackBola[i];
		taskprop.stacksize = stacksize;
		taskprop.taskentry = task__Mov_Bola;
		
		KS_DefTaskProp (taskBola[i], &taskprop);
		/* Parametros argumento */
		indiceBola[i]=i;
		KS_DefTaskEnvArg (taskBola[i], &indiceBola[i]);
		KS_ExecuteTask (taskBola[i]);
	}
	// Ambiente grafico
	initgraph(&GraphDriver, &GraphMode, "", 607, 600);
	
	while(!quit)
	{
		// Checar STDIN
		if(kbhit())
		{
			// q - quit
			if(GetKeyState(81) & 0x8000)
			{
				quit = true;
			}
			// w 87
			if(GetKeyState(87) & 0x8000)
			{
				KS_TestMutxW(M_P1);
				if(player1.v1.y-INC_PLAYER>TOPO)
				{
					player1.v1.y-=INC_PLAYER;
					player1.v2.y-=INC_PLAYER;
				}
				else
				{
					player1.v2.y-=(player1.v1.y-TOPO-1);
					player1.v1.y-=(player1.v1.y-TOPO-1);
				}
				KS_ReleaseMutx(M_P1);
			}
			// s 83
			if(GetKeyState(83) & 0x8000)
			{
				KS_TestMutxW(M_P1);
				if(player1.v2.y+INC_PLAYER<INFERIOR)
				{
					player1.v1.y+=INC_PLAYER;
					player1.v2.y+=INC_PLAYER;
				}
				else
				{
					player1.v1.y+=(INFERIOR - player1.v2.y -1);
					player1.v2.y+=(INFERIOR - player1.v2.y -1);
				}
				KS_ReleaseMutx(M_P1);
			}
			// i 73
			if(GetKeyState(73) & 0x8000)
			{
				KS_TestMutxW(M_P2);
				if(player2.v1.y-INC_PLAYER>TOPO)
				{
					player2.v1.y-=INC_PLAYER;
					player2.v2.y-=INC_PLAYER;
				}
				else
				{
					player2.v2.y-=(player2.v1.y-TOPO-1);
					player2.v1.y-=(player2.v1.y-TOPO-1);
				}
				KS_ReleaseMutx(M_P2);
			}
			// k 75
			if(GetKeyState(75) & 0x8000)
			{
				KS_TestMutxW(M_P2);
				if(player2.v2.y+INC_PLAYER<INFERIOR)
				{
					player2.v1.y+=INC_PLAYER;
					player2.v2.y+=INC_PLAYER;
				}
				else
				{
					player2.v1.y+=(INFERIOR - player2.v2.y -1);
					player2.v2.y+=(INFERIOR - player2.v2.y -1);
				}
				KS_ReleaseMutx(M_P2);
			}
		}
		KS_ScheduleThread(_Display);
		KS_SleepTask(SYSTIMER, (TICKS)100-(velocidade*10)/CLKTICK);
	}
	// Fechar Ambiente Grafico
	closegraph();
	
	for (int i=0;i<qtdBola;i++)
	{
		KS_TerminateTask(taskBola[i]);
	}
	brkflag=1;
	KS_TerminateTask(SELFTASK);
}
