// aoptions.h - RTXC Quadros Version 1.0.0 Application options

// This file was generated on 11/05/2013 23:02:14 -- RTXCgen v1.12 Build 411

/*
 *    RTXC Quadros Version 1.0.0
 *    Copyright (c) 1999-2013
 *    Quadros Systems, Inc.
 *    ALL RIGHTS RESERVED
 *
 *    THE INFORMATION HEREIN IS CONFIDENTIAL AND PROPRIETARY.
 *    UNAUTHORIZED DISCLOSURE OR DISTRIBUTION IS PROHIBITED.
*/

/*
 *            ** WARNING **
 *
 *    Do **NOT** Edit this File by Hand
 *
 *    It was computer-generated by RTXCgen from
 *    an Application specification file.
*/

//     Project Name: Exemplo-modelo
//         CPU Name: CPU name
// Application Name: Application name

#ifndef _AOPTIONS_H // {
#define _AOPTIONS_H

// Begin - Revision Information, Top
// End - Revision Information, Top

#undef HAS_UserTraceMode // Kernel Options

// Class Level Attributes

#define HAS_LevelStatistics
#undef HAS_LevelDiagnosticMode
#undef HAS_LevelTraceMode

#define HAS_ThreadStatistics
#undef HAS_ThreadDiagnosticMode
#undef HAS_ThreadTraceMode

#define HAS_ExceptionStatistics
#undef HAS_ExceptionDiagnosticMode
#undef HAS_ExceptionTraceMode

#define HAS_EventSourceStatistics
#undef HAS_EventSourceDiagnosticMode
#undef HAS_EventSourceTraceMode

#define HAS_CounterStatistics
#undef HAS_CounterDiagnosticMode
#undef HAS_CounterTraceMode

#define HAS_AlarmStatistics
#undef HAS_AlarmDiagnosticMode
#undef HAS_AlarmTraceMode

#define HAS_PipeStatistics
#undef HAS_PipeDiagnosticMode
#undef HAS_PipeTraceMode

#define HAS_TaskStatistics
#undef HAS_TaskDiagnosticMode
#undef HAS_TaskTraceMode

#define HAS_SemaphoreStatistics
#undef HAS_SemaphoreDiagnosticMode
#undef HAS_SemaphoreTraceMode

#define HAS_QueueStatistics
#undef HAS_QueueDiagnosticMode
#undef HAS_QueueTraceMode

#define HAS_MailboxStatistics
#undef HAS_MailboxDiagnosticMode
#undef HAS_MailboxTraceMode

#define HAS_PartitionStatistics
#undef HAS_PartitionDiagnosticMode
#undef HAS_PartitionTraceMode

#define HAS_MutexStatistics
#undef HAS_MutexDiagnosticMode
#undef HAS_MutexTraceMode

// Consolidated Class Wide Attributes
#define HAS_Statistics
#undef HAS_DiagnosticMode
#undef HAS_KernelTraceMode


#define MAX_THREADS_PER_LEVEL 1 // Largest number of threads for any level

#define HAS_FLOATING_ANCHOR // Floating anchor
#define ANCHOR_ADDRESS 0x0 // Address of anchor

#undef HAS_EXTENDED_CONTEXT // Application has extended task context(s)

// Begin - User Include Information
// End - User Include Information

// Begin - Revision Information, Bottom
// End - Revision Information, Bottom

#endif // } _AOPTIONS_H

// end of file - aoptions.h
