// Bola.cpp - Generated by VisualRTXC

#include "ktask.h"
#include "rtxcapi.h"
#include "kproject.h"
#include "objetos.h"
#include "graphics.h"

extern circulo bola;

void task_Bola(void);

void task_Bola(void)
{
	bola.v.x=299;
	bola.v.y=199;
	bola.raio=10;
	bola.fillcolor=WHITE;
	KS_TerminateTask(SELFTASK);
}
