// DISPLAY.cpp - Generated by VisualRTXC

#include "rtxcapi.h"
#include "kproject.h"
#include "objetos.h"
#include "graphics.h"
#include <stdio.h>

extern tabuleiro t;
extern quadrilatero player1;
extern quadrilatero player2;
extern circulo bola;
extern int scoreP1;
extern int scoreP2;
char SscoreP1[3];
char SscoreP2[3];

void thrd_DISPLAY(void *ThreadArg, void *ThreadEnvArg);

void thrd_DISPLAY(void *ThreadArg, void *ThreadEnvArg)
{
	//static int i = 0;
	setbkcolor(BLACK);
	cleardevice();
	
	// Score
	sprintf(SscoreP1, "%d", scoreP1);
	sprintf(SscoreP2, "%d", scoreP2);
	outtextxy(300,50,"Score:");
	outtextxy(300,60,"---------------");
	outtextxy(300,70,"Player 1:");
	outtextxy(380,70,SscoreP1);
	outtextxy(300,90,"Player 2:");
	outtextxy(380,90,SscoreP2);

	// Cor tabuleiro
	setfillstyle(t.filltype, t.fillcolor);

	// Lados Tabuleiro
	for(int i=0;i<4;i++)
	{
		bar(	t.lado[i].v1.x, t.lado[i].v1.y,
				t.lado[i].v2.x, t.lado[i].v2.y);
		
	}
	// Player 1
	setfillstyle(player1.filltype, player1.fillcolor);
	bar(	player1.v1.x, player1.v1.y,
			player1.v2.x, player1.v2.y);
	// Player 2
	setfillstyle(player2.filltype, player2.fillcolor);
	bar(	player2.v1.x, player2.v1.y,
			player2.v2.x, player2.v2.y);
	// Bola
	setfillstyle(bola.filltype, bola.fillcolor);
	circle(bola.v.x, bola.v.y, bola.raio);
}
