// DISPLAY.cpp - Generated by VisualRTXC

#include "rtxcapi.h"
#include "kproject.h"
#include "objetos.h"
#include "graphics.h"

extern tabuleiro t;
extern quadrilatero player1;
extern quadrilatero player2;
extern circulo bola;

void thrd_DISPLAY(void *ThreadArg, void *ThreadEnvArg);

void thrd_DISPLAY(void *ThreadArg, void *ThreadEnvArg)
{
	//static int i = 0;
	setbkcolor(BLACK);
	cleardevice();
	
	// Cor tabuleiro
	setfillstyle(t.filltype, t.fillcolor);
	// Lados Tabuleiro
	for(int i=0;i<4;i++)
	{
		bar(	t.lado[i].v1.x, t.lado[i].v1.y,
				t.lado[i].v2.x, t.lado[i].v2.y);
		
	}
	// Player 1
	setfillstyle(player1.filltype, player1.fillcolor);
	bar(	player1.v1.x, player1.v1.y,
			player1.v2.x, player1.v2.y);
	// Player 2
	setfillstyle(player2.filltype, player2.fillcolor);
	bar(	player2.v1.x, player2.v1.y,
			player2.v2.x, player2.v2.y);
	// Bola
	setfillstyle(bola.filltype, bola.fillcolor);
	circle(bola.v.x, bola.v.y, bola.raio);
}
