// kcounter.h - RTXC Quadros Version 1.0.0 Counter include file

// This file was generated on 11/08/2013 20:39:15 -- RTXCgen v1.12 Build 411

/*
 *    RTXC Quadros Version 1.0.0
 *    Copyright (c) 1999-2013
 *    Quadros Systems, Inc.
 *    ALL RIGHTS RESERVED
 *
 *    THE INFORMATION HEREIN IS CONFIDENTIAL AND PROPRIETARY.
 *    UNAUTHORIZED DISCLOSURE OR DISTRIBUTION IS PROHIBITED.
*/

/*
 *            ** WARNING **
 *
 *    Do **NOT** Edit this File by Hand
 *
 *    It was computer-generated by RTXCgen from
 *    an Application specification file.
*/

//     Project Name: Pong
//         CPU Name: CPU name
// Application Name: Pong

#ifndef _KCOUNTER_H // {
#define _KCOUNTER_H

// Begin - Revision Information, Top
// End - Revision Information, Top

#define NCOUNTERS 1

#define DNCOUNTERS 0

#define SYSTIMER 1

#define COUNTER_NAMMAX 8

// Begin - User Include Information
// End - User Include Information

// Begin - Revision Information, Bottom
// End - Revision Information, Bottom

#endif // } _KCOUNTER_H

// end of file - kcounter.h
