// kcounter.cpp - RTXC Quadros Version 1.0.0 Counter definitions

// This file was generated on 11/08/2013 20:39:15 -- RTXCgen v1.12 Build 411

/*
 *    RTXC Quadros Version 1.0.0
 *    Copyright (c) 1999-2013
 *    Quadros Systems, Inc.
 *    ALL RIGHTS RESERVED
 *
 *    THE INFORMATION HEREIN IS CONFIDENTIAL AND PROPRIETARY.
 *    UNAUTHORIZED DISCLOSURE OR DISTRIBUTION IS PROHIBITED.
*/

/*
 *            ** WARNING **
 *
 *    Do **NOT** Edit this File by Hand
 *
 *    It was computer-generated by RTXCgen from
 *    an Application specification file.
*/

//     Project Name: Pong
//         CPU Name: CPU name
// Application Name: Pong

#include "rtxcapi.h"

#ifdef HAS_Counters // {

#include "kevntsrc.h"
#include "kcounter.h"

// Begin - Revision Information, Top
// End - Revision Information, Top


#ifdef HAS_CounterStaticNames // {
// Static Object Name Array
static const char countername[1 + NCOUNTERS][COUNTER_NAMMAX + 1] =
{
    ""   // 0 - Not Used
   ,"SYSTIMER"   // 1 - 
};
#endif // } HAS_CounterStaticNames

// Class Properties
extern const KCLASSPROP counterclassprop =
{
   ATTR_STATISTICS |
   ATTR_STATIC_NAMES | ATTR_DYNAMICS,
   NCOUNTERS,
   DNCOUNTERS,
   sizeof(CCHEADER),
   ((NCOUNTERS + DNCOUNTERS) * sizeof(CCHEADER)) + (DNCOUNTERS * sizeof(NAMELIST)),

#ifdef HAS_CounterStaticNames // {
   COUNTER_NAMMAX,
   &countername[0][0]

#else
   0,
   (const char *)0
#endif // } HAS_CounterStaticNames

};

// Begin - User Include Information
// End - User Include Information

// Object Properties
extern const COUNTERPROP counterprop[1 + NCOUNTERS] =
{
    { 0, 0, 0 } // 0 - Not Used
   ,{ ATTR_COUNTER_TIMEBASE | ATTR_COUNTER_TICKSLICE, EVNTSRC1, 1 } // 1 SYSTIMER - 
};

// Begin - Revision Information, Bottom
// End - Revision Information, Bottom

#endif // } HAS_Counters

// end of file - kcounter.cpp
