// kevntsrc.cpp - RTXC Quadros Version 1.0.0 Event Source definitions

// This file was generated on 11/06/2013 11:51:39 -- RTXCgen v1.12 Build 411

/*
 *    RTXC Quadros Version 1.0.0
 *    Copyright (c) 1999-2013
 *    Quadros Systems, Inc.
 *    ALL RIGHTS RESERVED
 *
 *    THE INFORMATION HEREIN IS CONFIDENTIAL AND PROPRIETARY.
 *    UNAUTHORIZED DISCLOSURE OR DISTRIBUTION IS PROHIBITED.
*/

/*
 *            ** WARNING **
 *
 *    Do **NOT** Edit this File by Hand
 *
 *    It was computer-generated by RTXCgen from
 *    an Application specification file.
*/

//     Project Name: Pong
//         CPU Name: CPU name
// Application Name: Pong

#include "rtxcapi.h"

#ifdef HAS_EventSources // {

#include "kevntsrc.h"

// Begin - Revision Information, Top
// End - Revision Information, Top


#ifdef HAS_EventSourceStaticNames // {
// Static Object Name Array
static const char evntsrcname[1 + NEVNTSRCS][EVNTSRC_NAMMAX + 1] =
{
    ""   // 0 - Not Used
   ,"EVNTSRC1"   // 1 - 
};
#endif // } HAS_EventSourceStaticNames

// Class Properties
extern const KCLASSPROP evntsrcclassprop =
{
   ATTR_STATISTICS |
   ATTR_STATIC_NAMES | ATTR_DYNAMICS,
   NEVNTSRCS,
   DNEVNTSRCS,
   sizeof(SCHEADER),
   ((NEVNTSRCS + DNEVNTSRCS) * sizeof(SCHEADER)) + (DNEVNTSRCS * sizeof(NAMELIST)),

#ifdef HAS_EventSourceStaticNames // {
   EVNTSRC_NAMMAX,
   &evntsrcname[0][0]

#else
   0,
   (const char *)0
#endif // } HAS_EventSourceStaticNames

};

// Begin - User Include Information
// End - User Include Information

// Object Properties
extern const EVNTSRCPROP evntsrcprop[1 + NEVNTSRCS] =
{
    { 0 } // 0 - Not Used
   ,{ 0 } // 1 EVNTSRC1 - 
};

// Begin - Revision Information, Bottom
// End - Revision Information, Bottom

#endif // } HAS_EventSources

// end of file - kevntsrc.cpp
