// kexcptn.h - RTXC Quadros Version 1.0.0 Exception include file

// This file was generated on 11/05/2013 23:25:55 -- RTXCgen v1.12 Build 411

/*
 *    RTXC Quadros Version 1.0.0
 *    Copyright (c) 1999-2013
 *    Quadros Systems, Inc.
 *    ALL RIGHTS RESERVED
 *
 *    THE INFORMATION HEREIN IS CONFIDENTIAL AND PROPRIETARY.
 *    UNAUTHORIZED DISCLOSURE OR DISTRIBUTION IS PROHIBITED.
*/

/*
 *            ** WARNING **
 *
 *    Do **NOT** Edit this File by Hand
 *
 *    It was computer-generated by RTXCgen from
 *    an Application specification file.
*/

//     Project Name: Pong
//         CPU Name: CPU name
// Application Name: Pong

#ifndef _KEXCPTN_H // {
#define _KEXCPTN_H

// Begin - Revision Information, Top
// End - Revision Information, Top

#define NEXCPTNS 2

#define DNEXCPTNS 5

#define TMR0ISR 1 // Timer 0 Interrupt Service Routine
#define UART0ISR 2

#define EXCPTN_NAMMAX 8

// Begin - User Include Information
// End - User Include Information

// Begin - Revision Information, Bottom
// End - Revision Information, Bottom

#endif // } _KEXCPTN_H

// end of file - kexcptn.h
