// Keyboard.cpp - Generated by VisualRTXC

#include "ktask.h"
#include "rtxcapi.h"
#include "kproject.h"
#include "objetos.h"
#include "graphics.h"
extern bool quit;

void task_Keyboard(void);

void task_Keyboard(void)
{
	int key=0;
	KS_TerminateTask(SELFTASK);
}
