// klevel.cpp - RTXC Quadros Version 1.0.0 Level definitions

// This file was generated on 11/06/2013 21:55:37 -- RTXCgen v1.12 Build 411

/*
 *    RTXC Quadros Version 1.0.0
 *    Copyright (c) 1999-2013
 *    Quadros Systems, Inc.
 *    ALL RIGHTS RESERVED
 *
 *    THE INFORMATION HEREIN IS CONFIDENTIAL AND PROPRIETARY.
 *    UNAUTHORIZED DISCLOSURE OR DISTRIBUTION IS PROHIBITED.
*/

/*
 *            ** WARNING **
 *
 *    Do **NOT** Edit this File by Hand
 *
 *    It was computer-generated by RTXCgen from
 *    an Application specification file.
*/

//     Project Name: Pong
//         CPU Name: CPU name
// Application Name: Pong

#include "rtxcapi.h"

#ifdef HAS_Levels // {

#include "klevel.h"

// Begin - Revision Information, Top
// End - Revision Information, Top


#ifdef HAS_LevelStaticNames // {
// Static Object Name Array
static const char levelname[1 + NLEVELS][LEVEL_NAMMAX + 1] =
{
    ""   // 0 - Not Used
   ,"LEVEL1"   // 1 - 
};
#endif // } HAS_LevelStaticNames

// Class Properties
extern const KCLASSPROP levelclassprop =
{
   ATTR_STATISTICS |
   ATTR_STATIC_NAMES,
   NLEVELS,
   DNLEVELS,
   sizeof(LCHEADER),
   ((NLEVELS + DNLEVELS) * sizeof(LCHEADER)) + (DNLEVELS * sizeof(NAMELIST)),

#ifdef HAS_LevelStaticNames // {
   LEVEL_NAMMAX,
   &levelname[0][0]

#else
   0,
   (const char *)0
#endif // } HAS_LevelStaticNames

};

// Begin - User Include Information
// End - User Include Information

// Object Properties
extern const LEVELPROP levelprop[1 + NLEVELS] =
{
    { 0, 0, 0 } // 0 - Not Used
   ,{ 0, 1, 0 } // 1 LEVEL1 - 
};

// Begin - Revision Information, Bottom
// End - Revision Information, Bottom

#endif // } HAS_Levels

// end of file - klevel.cpp
