// klevel.h - RTXC Quadros Version 1.0.0 Level include file

// This file was generated on 11/06/2013 11:51:39 -- RTXCgen v1.12 Build 411

/*
 *    RTXC Quadros Version 1.0.0
 *    Copyright (c) 1999-2013
 *    Quadros Systems, Inc.
 *    ALL RIGHTS RESERVED
 *
 *    THE INFORMATION HEREIN IS CONFIDENTIAL AND PROPRIETARY.
 *    UNAUTHORIZED DISCLOSURE OR DISTRIBUTION IS PROHIBITED.
*/

/*
 *            ** WARNING **
 *
 *    Do **NOT** Edit this File by Hand
 *
 *    It was computer-generated by RTXCgen from
 *    an Application specification file.
*/

//     Project Name: Pong
//         CPU Name: CPU name
// Application Name: Pong

#ifndef _KLEVEL_H // {
#define _KLEVEL_H

// Begin - Revision Information, Top
// End - Revision Information, Top

#define NLEVELS 1

#define DNLEVELS 0

#define LEVEL1 1

#define LEVEL_NAMMAX 8

// Begin - User Include Information
// End - User Include Information

// Begin - Revision Information, Bottom
// End - Revision Information, Bottom

#endif // } _KLEVEL_H

// end of file - klevel.h
