// kmbox.h - RTXC Quadros Version 1.0.0 Mailbox include file

// This file was generated on 11/05/2013 23:02:14 -- RTXCgen v1.12 Build 411

/*
 *    RTXC Quadros Version 1.0.0
 *    Copyright (c) 1999-2013
 *    Quadros Systems, Inc.
 *    ALL RIGHTS RESERVED
 *
 *    THE INFORMATION HEREIN IS CONFIDENTIAL AND PROPRIETARY.
 *    UNAUTHORIZED DISCLOSURE OR DISTRIBUTION IS PROHIBITED.
*/

/*
 *            ** WARNING **
 *
 *    Do **NOT** Edit this File by Hand
 *
 *    It was computer-generated by RTXCgen from
 *    an Application specification file.
*/

//     Project Name: Exemplo-modelo
//         CPU Name: CPU name
// Application Name: Application name

#ifndef _KMBOX_H // {
#define _KMBOX_H

// Begin - Revision Information, Top
// End - Revision Information, Top

#define NMBOXES 0

#define DNMBOXES 0


#define MBOX_NAMMAX 8

// Begin - User Include Information
// End - User Include Information

// Begin - Revision Information, Bottom
// End - Revision Information, Bottom

#endif // } _KMBOX_H

// end of file - kmbox.h
