// kmbox.cpp - RTXC Quadros Version 1.0.0 Mailbox definitions

// This file was generated on 11/05/2013 23:02:14 -- RTXCgen v1.12 Build 411

/*
 *    RTXC Quadros Version 1.0.0
 *    Copyright (c) 1999-2013
 *    Quadros Systems, Inc.
 *    ALL RIGHTS RESERVED
 *
 *    THE INFORMATION HEREIN IS CONFIDENTIAL AND PROPRIETARY.
 *    UNAUTHORIZED DISCLOSURE OR DISTRIBUTION IS PROHIBITED.
*/

/*
 *            ** WARNING **
 *
 *    Do **NOT** Edit this File by Hand
 *
 *    It was computer-generated by RTXCgen from
 *    an Application specification file.
*/

//     Project Name: Exemplo-modelo
//         CPU Name: CPU name
// Application Name: Application name

#include "rtxcapi.h"

#ifdef HAS_Mailboxes // {

#include "kmbox.h"

// Begin - Revision Information, Top
// End - Revision Information, Top


#ifdef HAS_MailboxStaticNames // {
// Static Object Name Array
static const char mboxname[1 + NMBOXES][MBOX_NAMMAX + 1] =
{
    ""   // 0 - Not Used
};
#endif // } HAS_MailboxStaticNames

// Class Properties
extern const KCLASSPROP mboxclassprop =
{
   ATTR_STATISTICS |
   ATTR_STATIC_NAMES | ATTR_DYNAMICS | ATTR_SEMAPHORES,
   NMBOXES,
   DNMBOXES,
   sizeof(MHEADER),
   ((NMBOXES + DNMBOXES) * sizeof(MHEADER)) + (DNMBOXES * sizeof(NAMELIST)),

#ifdef HAS_MailboxStaticNames // {
   MBOX_NAMMAX,
   &mboxname[0][0]

#else
   0,
   (const char *)0
#endif // } HAS_MailboxStaticNames

};

// Begin - User Include Information
// End - User Include Information

// Object Properties
extern const MBOXPROP mboxprop[1 + NMBOXES] =
{
    { 0 } // 0 - Not Used
};

// Begin - Revision Information, Bottom
// End - Revision Information, Bottom

#endif // } HAS_Mailboxes

// end of file - kmbox.cpp
