// kmutx.h - RTXC Quadros Version 1.0.0 Mutex include file

// This file was generated on 10/30/2013 23:04:58 -- RTXCgen v1.12 Build 411

/*
 *    RTXC Quadros Version 1.0.0
 *    Copyright (c) 1999-2013
 *    Quadros Systems, Inc.
 *    ALL RIGHTS RESERVED
 *
 *    THE INFORMATION HEREIN IS CONFIDENTIAL AND PROPRIETARY.
 *    UNAUTHORIZED DISCLOSURE OR DISTRIBUTION IS PROHIBITED.
*/

/*
 *            ** WARNING **
 *
 *    Do **NOT** Edit this File by Hand
 *
 *    It was computer-generated by RTXCgen from
 *    an Application specification file.
*/

//     Project Name: Exemplo-modelo
//         CPU Name: CPU name
// Application Name: Application name

#ifndef _KMUTX_H // {
#define _KMUTX_H

// Begin - Revision Information, Top
// End - Revision Information, Top

#define NMUTXES 5

#define DNMUTXES 0

#define CONAMUTX 1
#define POPPARAM 2
#define M_PLOTQ 3
#define M_P1 4
#define M_P2 5

#define MUTX_NAMMAX 8

// Begin - User Include Information
// End - User Include Information

// Begin - Revision Information, Bottom
// End - Revision Information, Bottom

#endif // } _KMUTX_H

// end of file - kmutx.h
