// kpart.cpp - RTXC Quadros Version 1.0.0 Partition definitions

// This file was generated on 11/08/2013 20:39:15 -- RTXCgen v1.12 Build 411

/*
 *    RTXC Quadros Version 1.0.0
 *    Copyright (c) 1999-2013
 *    Quadros Systems, Inc.
 *    ALL RIGHTS RESERVED
 *
 *    THE INFORMATION HEREIN IS CONFIDENTIAL AND PROPRIETARY.
 *    UNAUTHORIZED DISCLOSURE OR DISTRIBUTION IS PROHIBITED.
*/

/*
 *            ** WARNING **
 *
 *    Do **NOT** Edit this File by Hand
 *
 *    It was computer-generated by RTXCgen from
 *    an Application specification file.
*/

//     Project Name: Pong
//         CPU Name: CPU name
// Application Name: Pong

#include "rtxcapi.h"

#ifdef HAS_Partitions // {

#include "kpart.h"

// Begin - Revision Information, Top
// End - Revision Information, Top


#ifdef HAS_PartitionStaticNames // {
// Static Object Name Array
static const char partname[1 + NPARTS][PART_NAMMAX + 1] =
{
    ""   // 0 - Not Used
   ,"STKPART"   // 1 - 
};
#endif // } HAS_PartitionStaticNames

// Class Properties
extern const KCLASSPROP partclassprop =
{
   ATTR_STATISTICS |
   ATTR_STATIC_NAMES | ATTR_DYNAMICS | ATTR_SEMAPHORES,
   NPARTS,
   DNPARTS,
   sizeof(PHEADER),
   ((NPARTS + DNPARTS) * sizeof(PHEADER)) + (DNPARTS * sizeof(NAMELIST)),

#ifdef HAS_PartitionStaticNames // {
   PART_NAMMAX,
   &partname[0][0]

#else
   0,
   (const char *)0
#endif // } HAS_PartitionStaticNames

};

// Begin - User Include Information
// End - User Include Information

// Partition Information

#define M1SZ 1024
#define M1CT 8
static char part1[M1CT * M1SZ]; // 1 STKPART - 


// Object Properties
extern const PARTPROP partprop[1 + NPARTS] =
{
    { 0, (char *)0, 0, 0 } // 0 - Not Used
   ,{ 0, &part1[0], M1SZ, M1CT } // 1 STKPART - 
};

// Begin - Revision Information, Bottom
// End - Revision Information, Bottom

#endif // } HAS_Partitions

// end of file - kpart.cpp
