// kpipe.h - RTXC Quadros Version 1.0.0 Pipe include file

// This file was generated on 11/03/2013 22:03:50 -- RTXCgen v1.12 Build 411

/*
 *    RTXC Quadros Version 1.0.0
 *    Copyright (c) 1999-2013
 *    Quadros Systems, Inc.
 *    ALL RIGHTS RESERVED
 *
 *    THE INFORMATION HEREIN IS CONFIDENTIAL AND PROPRIETARY.
 *    UNAUTHORIZED DISCLOSURE OR DISTRIBUTION IS PROHIBITED.
*/

/*
 *            ** WARNING **
 *
 *    Do **NOT** Edit this File by Hand
 *
 *    It was computer-generated by RTXCgen from
 *    an Application specification file.
*/

//     Project Name: Exemplo-modelo
//         CPU Name: CPU name
// Application Name: Application name

#ifndef _KPIPE_H // {
#define _KPIPE_H

// Begin - Revision Information, Top
// End - Revision Information, Top

#define NPIPES 0

#define DNPIPES 0


#define PIPE_NAMMAX 8

// Begin - User Include Information
// End - User Include Information

// Begin - Revision Information, Bottom
// End - Revision Information, Bottom

#endif // } _KPIPE_H

// end of file - kpipe.h
