// kproject.cpp - RTXC Quadros Version 1.0.0 Project Configuration definitions

// This file was generated on 11/05/2013 13:59:28 -- RTXCgen v1.12 Build 411

/*
 *    RTXC Quadros Version 1.0.0
 *    Copyright (c) 1999-2013
 *    Quadros Systems, Inc.
 *    ALL RIGHTS RESERVED
 *
 *    THE INFORMATION HEREIN IS CONFIDENTIAL AND PROPRIETARY.
 *    UNAUTHORIZED DISCLOSURE OR DISTRIBUTION IS PROHIBITED.
*/

/*
 *            ** WARNING **
 *
 *    Do **NOT** Edit this File by Hand
 *
 *    It was computer-generated by RTXCgen from
 *    an Application specification file.
*/

//     Project Name: Exemplo-modelo
//         CPU Name: CPU name
// Application Name: Application name

#include "rtxcapi.h"

#include "kproject.h"

// Begin - Revision Information, Top
// End - Revision Information, Top


#ifdef HAS_Threads // {
extern const KCLASSPROP levelclassprop;
extern const LEVELPROP levelprop[];
#endif // } HAS_Threads

static char sysram[SYSRAMSIZE];

extern const SYSPROP sysprop =
{
   KERNEL_ATTR,
   KERNEL_VERSION,
   sysram,
   SYSRAMSIZE,
   (char *)0,
   KSTACKSIZE,

#ifdef HAS_Threads // {
   &levelclassprop,
   levelprop,

#else
   (KCLASSPROP *)0,
   0,
#endif // } HAS_Threads

   0, // reserved
   0  // reserved
};

// Begin - User Include Information
// End - User Include Information


// Begin - Revision Information, Bottom
// End - Revision Information, Bottom

// end of file - kproject.cpp
