// ktask.h - RTXC Quadros Version 1.0.0 Task include file

// This file was generated on 11/08/2013 20:39:15 -- RTXCgen v1.12 Build 411

/*
 *    RTXC Quadros Version 1.0.0
 *    Copyright (c) 1999-2013
 *    Quadros Systems, Inc.
 *    ALL RIGHTS RESERVED
 *
 *    THE INFORMATION HEREIN IS CONFIDENTIAL AND PROPRIETARY.
 *    UNAUTHORIZED DISCLOSURE OR DISTRIBUTION IS PROHIBITED.
*/

/*
 *            ** WARNING **
 *
 *    Do **NOT** Edit this File by Hand
 *
 *    It was computer-generated by RTXCgen from
 *    an Application specification file.
*/

//     Project Name: Pong
//         CPU Name: CPU name
// Application Name: Pong

#ifndef _KTASK_H // {
#define _KTASK_H

// Begin - Revision Information, Top
// End - Revision Information, Top

#define NTASKS 6

#define DNTASKS 10

#define CONOTASK 1
#define CONITASK 2
#define _Principal 3
#define _Tabuleiro 4
#define _Player1 5
#define _Player2 6

#define TASK_NAMMAX 20

// Begin - User Include Information
// End - User Include Information

// Begin - Revision Information, Bottom
// End - Revision Information, Bottom

#endif // } _KTASK_H

// end of file - ktask.h
