// ktask.cpp - RTXC Quadros Version 1.0.0 Task definitions

// This file was generated on 11/06/2013 21:55:37 -- RTXCgen v1.12 Build 411

/*
 *    RTXC Quadros Version 1.0.0
 *    Copyright (c) 1999-2013
 *    Quadros Systems, Inc.
 *    ALL RIGHTS RESERVED
 *
 *    THE INFORMATION HEREIN IS CONFIDENTIAL AND PROPRIETARY.
 *    UNAUTHORIZED DISCLOSURE OR DISTRIBUTION IS PROHIBITED.
*/

/*
 *            ** WARNING **
 *
 *    Do **NOT** Edit this File by Hand
 *
 *    It was computer-generated by RTXCgen from
 *    an Application specification file.
*/

//     Project Name: Pong
//         CPU Name: CPU name
// Application Name: Pong

#include "rtxcapi.h"

#ifdef HAS_Tasks // {

#include "ktask.h"

// Begin - Revision Information, Top
// End - Revision Information, Top


#ifdef HAS_TaskStaticNames // {
// Static Object Name Array
static const char taskname[1 + NTASKS][TASK_NAMMAX + 1] =
{
    ""   // 0 - Not Used
   ,"CONOTASK"   // 1 - 
   ,"CONITASK"   // 2 - 
   ,"_Principal"   // 3 - 
   ,"_Tabuleiro"   // 4 - 
   ,"_Player1"   // 5 - 
   ,"_Player2"   // 6 - 
};
#endif // } HAS_TaskStaticNames

// Class Properties
extern const KCLASSPROP taskclassprop =
{
   ATTR_STATISTICS |
   ATTR_STATIC_NAMES | ATTR_DYNAMICS | ATTR_SEMAPHORES | ATTR_TICKSLICE | ATTR_ARGUMENTS,
   NTASKS,
   DNTASKS,
   sizeof(TCB),
   ((1 + NTASKS + DNTASKS) * sizeof(TCB)) + (DNTASKS * sizeof(NAMELIST)),

#ifdef HAS_TaskStaticNames // {
   TASK_NAMMAX,
   &taskname[0][0]

#else
   0,
   (const char *)0
#endif // } HAS_TaskStaticNames

};

// Begin - User Include Information
// End - User Include Information

// Task Information

#define STKSZ1 256 // 1 CONOTASK - 
static STK_ALIGNTYPE stack1[STKSZ1 / SIZEOF_STK_ALIGNTYPE];
extern void task_CONOTASK(void);

#define STKSZ2 256 // 2 CONITASK - 
static STK_ALIGNTYPE stack2[STKSZ2 / SIZEOF_STK_ALIGNTYPE];
extern void task_CONITASK(void);

#define STKSZ3 512 // 3 _Principal - 
static STK_ALIGNTYPE stack3[STKSZ3 / SIZEOF_STK_ALIGNTYPE];
extern void task__Principal(void);

#define STKSZ4 512 // 4 _Tabuleiro - 
static STK_ALIGNTYPE stack4[STKSZ4 / SIZEOF_STK_ALIGNTYPE];
extern void task__Tabuleiro(void);

#define STKSZ5 512 // 5 _Player1 - 
static STK_ALIGNTYPE stack5[STKSZ5 / SIZEOF_STK_ALIGNTYPE];
extern void task__Player1(void);

#define STKSZ6 512 // 6 _Player2 - 
static STK_ALIGNTYPE stack6[STKSZ6 / SIZEOF_STK_ALIGNTYPE];
extern void task__Player2(void);


// Starting Order Task List
extern const TASK startls[] =
{
   CONITASK, // (3) 2 - 
   CONOTASK, // (4) 1 - 
   _Principal, // (10) 3 - 
   _Tabuleiro, // (10) 4 - 
   _Player1, // (10) 5 - 
   _Player2, // (10) 6 - 
   0 // Null-terminated Task List
};

// Object Properties
extern const TASKPROP taskprop[1 + NTASKS] =
{
    {  (void (*)(void))0, (char *)0, 0, 0 } // 0 - Not Used
   ,{  task_CONOTASK, (char *)stack1, STKSZ1, 4 } // 1 CONOTASK - 
   ,{  task_CONITASK, (char *)stack2, STKSZ2, 3 } // 2 CONITASK - 
   ,{  task__Principal, (char *)stack3, STKSZ3, 10 } // 3 _Principal - 
   ,{  task__Tabuleiro, (char *)stack4, STKSZ4, 9 } // 4 _Tabuleiro - 
   ,{  task__Player1, (char *)stack5, STKSZ5, 9 } // 5 _Player1 - 
   ,{  task__Player2, (char *)stack6, STKSZ6, 9 } // 6 _Player2 - 
};

// Begin - Revision Information, Bottom
// End - Revision Information, Bottom

#endif // } HAS_Tasks

// end of file - ktask.cpp
