// ktask.h - RTXC Quadros Version 1.0.0 Task include file

// This file was generated on 11/06/2013 11:51:39 -- RTXCgen v1.12 Build 411

/*
 *    RTXC Quadros Version 1.0.0
 *    Copyright (c) 1999-2013
 *    Quadros Systems, Inc.
 *    ALL RIGHTS RESERVED
 *
 *    THE INFORMATION HEREIN IS CONFIDENTIAL AND PROPRIETARY.
 *    UNAUTHORIZED DISCLOSURE OR DISTRIBUTION IS PROHIBITED.
*/

/*
 *            ** WARNING **
 *
 *    Do **NOT** Edit this File by Hand
 *
 *    It was computer-generated by RTXCgen from
 *    an Application specification file.
*/

//     Project Name: Pong
//         CPU Name: CPU name
// Application Name: Pong

#ifndef _KTASK_H // {
#define _KTASK_H

// Begin - Revision Information, Top
// End - Revision Information, Top

#define NTASKS 7

#define DNTASKS 10

#define CONOTASK 1
#define CONITASK 2
#define Principal 3
#define Tabuleiro 4
#define Player1 5
#define Player2 6
#define Bola 7

#define TASK_NAMMAX 20

// Begin - User Include Information
// End - User Include Information

// Begin - Revision Information, Bottom
// End - Revision Information, Bottom

#endif // } _KTASK_H

// end of file - ktask.h
