// ktask.h - RTXC Quadros Version 1.0.0 Task include file

// This file was generated on 11/03/2013 22:03:50 -- RTXCgen v1.12 Build 411

/*
 *    RTXC Quadros Version 1.0.0
 *    Copyright (c) 1999-2013
 *    Quadros Systems, Inc.
 *    ALL RIGHTS RESERVED
 *
 *    THE INFORMATION HEREIN IS CONFIDENTIAL AND PROPRIETARY.
 *    UNAUTHORIZED DISCLOSURE OR DISTRIBUTION IS PROHIBITED.
*/

/*
 *            ** WARNING **
 *
 *    Do **NOT** Edit this File by Hand
 *
 *    It was computer-generated by RTXCgen from
 *    an Application specification file.
*/

//     Project Name: Exemplo-modelo
//         CPU Name: CPU name
// Application Name: Application name

#ifndef _KTASK_H // {
#define _KTASK_H

// Begin - Revision Information, Top
// End - Revision Information, Top

#define NTASKS 9

#define DNTASKS 0

#define CONOTASK 1
#define CONITASK 2
#define Principal 3
#define Tabuleiro 4
#define Keyboard 5
#define Player1 6
#define Player2 7
#define Bola 8
#define Mov_Bola 9

#define TASK_NAMMAX 20

// Begin - User Include Information
// End - User Include Information

// Begin - Revision Information, Bottom
// End - Revision Information, Bottom

#endif // } _KTASK_H

// end of file - ktask.h
