// kthread.h - RTXC Quadros Version 1.0.0 Thread include file

// This file was generated on 11/05/2013 13:59:28 -- RTXCgen v1.12 Build 411

/*
 *    RTXC Quadros Version 1.0.0
 *    Copyright (c) 1999-2013
 *    Quadros Systems, Inc.
 *    ALL RIGHTS RESERVED
 *
 *    THE INFORMATION HEREIN IS CONFIDENTIAL AND PROPRIETARY.
 *    UNAUTHORIZED DISCLOSURE OR DISTRIBUTION IS PROHIBITED.
*/

/*
 *            ** WARNING **
 *
 *    Do **NOT** Edit this File by Hand
 *
 *    It was computer-generated by RTXCgen from
 *    an Application specification file.
*/

//     Project Name: Exemplo-modelo
//         CPU Name: CPU name
// Application Name: Application name

#ifndef _KTHREAD_H // {
#define _KTHREAD_H

// Begin - Revision Information, Top
// End - Revision Information, Top

#define NTHREADS 1

#define DNTHREADS 0

#define DISPLAY 1

#define THREAD_NAMMAX 8

// Begin - User Include Information
// End - User Include Information

// Begin - Revision Information, Bottom
// End - Revision Information, Bottom

#endif // } _KTHREAD_H

// end of file - kthread.h
