// Player1.cpp - Generated by VisualRTXC

#include "ktask.h"
#include "rtxcapi.h"
#include "kproject.h"
#include "objetos.h"
#include "graphics.h"

extern quadrilatero player1;

void task_Player1(void);

void task_Player1(void)
{
	// Player 1
	player1.v1.x=6;
	player1.v1.y=125;
	player1.v2.x=20;
	player1.v2.y=274;
	player1.filltype=SOLID_FILL;
	player1.fillcolor=7;
	
	KS_TerminateTask(SELFTASK);
}
