// Principal.cpp - Generated by VisualRTXC

#include "kcounter.h"
#include "kmutx.h"
#include "ktask.h"
#include "kthread.h"
#include <stdio.h>
#include <stdlib.h>
#include <windows.h>
#include "rtxcapi.h"
#include "kproject.h"
#include "objetos.h"
#include "graphics.h"

tabuleiro t;
quadrilatero player1;
quadrilatero player2;
circulo bola;
bool quit = false;
int scoreP1 = 0;
int scoreP2 = 0;

#define VELOCIDADE 15 // 0 - 99

void task_Principal(void);

void task_Principal(void)
{
	
	int key=0;
	//quadrado q;
	int GraphDriver = DETECT,GraphMode = 0;
	int i=0; 
	
	
	initgraph(&GraphDriver, &GraphMode, "", 607, 600);
	
	/*q.filltype=SOLID_FILL;
	q.fillcolor=3;
	q.x=300;
	q.y=300;
	q.width=100;
	q.height=100;		 */
	
	while(!quit)
	{
		// Verifica se ocorreu um evento
		if(kbhit())
		{
			key = getch();
			// w 87 e 119
			if(GetKeyState(87) & 0x8000)
			{
				KS_TestMutxW(M_P1);
				if(player1.v1.y-1>5)
				{
					player1.v1.y-=VELOCIDADE;
					player1.v2.y-=VELOCIDADE;
				}
				KS_ReleaseMutx(M_P1);
			}
			// s 83 e 115
			if(GetKeyState(83) & 0x8000)
			{
				KS_TestMutxW(M_P1);
				if(player1.v2.y+1<394)
				{
					player1.v1.y+=VELOCIDADE;
					player1.v2.y+=VELOCIDADE;
				}
				KS_ReleaseMutx(M_P1);
			}
			// i 73 e 105
			if(GetKeyState(73) & 0x8000)
			{
				KS_TestMutxW(M_P2);
				if(player2.v1.y-1>5)
				{
					player2.v1.y-=VELOCIDADE;
					player2.v2.y-=VELOCIDADE;
				}
				KS_ReleaseMutx(M_P2);
			}
			// k 75 e 107
			if(GetKeyState(75) & 0x8000)
			{
				KS_TestMutxW(M_P2);
				if(player2.v2.y+1<394)
				{
					player2.v1.y+=VELOCIDADE;
					player2.v2.y+=VELOCIDADE;
				}
				KS_ReleaseMutx(M_P2);
			}
			// q 81 e 113
			if(GetKeyState(81) & 0x8000)
			{
				quit=true;
			}
		}
		KS_ScheduleThread(DISPLAY);
		/*setbkcolor(BLACK);
		cleardevice();
		setfillstyle(q.filltype, q.fillcolor);
		bar(	(int)q.x+i - q.width/2,
				(int)q.y+i - q.height/2,
				(int)q.x+i + q.width/2,
				(int)q.y+i + q.height/2);
		i++;*/
		
		
		KS_SleepTask(SYSTIMER, (TICKS)100/CLKTICK);
	}
	closegraph();
	KS_TerminateTask(SELFTASK);
}
