// Tabuleiro.cpp - Generated by VisualRTXC

#include "ktask.h"
#include "rtxcapi.h"
#include "kproject.h"
#include "objetos.h"
#include "graphics.h"

extern tabuleiro t;

void task_Tabuleiro(void);

void task_Tabuleiro(void)
{
	// Cores
	t.filltype=SOLID_FILL;
	t.fillcolor=3;
	
	// Esquerda
	t.lado[0].v1.x=0;
	t.lado[0].v1.y=0;
	t.lado[0].v2.x=5;
	t.lado[0].v2.y=399;
	
	// Topo
	t.lado[1].v1.x=0;
	t.lado[1].v1.y=0;
	t.lado[1].v2.x=599;
	t.lado[1].v2.y=5;
	
	// Direita
	t.lado[2].v1.x=599-5;
	t.lado[2].v1.y=0;
	t.lado[2].v2.x=599;
	t.lado[2].v2.y=399;
	
	// Inferior
	t.lado[3].v1.x=0;
	t.lado[3].v1.y=399-5;
	t.lado[3].v2.x=599;
	t.lado[3].v2.y=399;
	KS_TerminateTask(SELFTASK);
}
