// uexcptn.s - RTXC Quadros Version 1.0.0 User Interrupts

// This file was generated on 09/04/2009 10:38:04 -- RTXCgen v1.12 Build 411


// RTXC Quadros Version 1.0.0
// Copyright (c) 1999-2009
// Quadros Systems, Inc.
// ALL RIGHTS RESERVED
//
// THE INFORMATION HEREIN IS CONFIDENTIAL AND PROPRIETARY.
// UNAUTHORIZED DISCLOSURE OR DISTRIBUTION IS PROHIBITED.



//         ** WARNING **
//
// Do **NOT** Edit this File by Hand
//
// It was computer-generated by RTXCgen from
// an Application specification file.


//     Project Name: Exemplo-modelo
//         CPU Name: CPU name
// Application Name: Application name

   .include "rtxcmac.inc"

// Begin - Revision Information, Top
// End - Revision Information, Top



   .extern excpt_TMR0ISR
TMR0ISR .equ 1 // Timer 0 Interrupt Service Routine
TMR0ISR_LEVEL .equ 2 // Interrupt level
TMR0ISR_VECTOR .equ 119 // Vector number


   .extern excpt_UART0ISR
UART0ISR .equ 2
UART0ISR_LEVEL .equ 1 // Interrupt level
UART0ISR_VECTOR .equ 77 // Vector number

// Begin - User Include Information
// End - User Include Information


   RTXCISRms isvcexcpt_TMR0ISR,excpt_TMR0ISR,TMR0ISR_LEVEL,TMR0ISR // 1 TMR0ISR - Timer 0 Interrupt Service Routine
   RTXCISRms isvcexcpt_UART0ISR,excpt_UART0ISR,UART0ISR_LEVEL,UART0ISR // 2 UART0ISR - 

// Begin - Revision Information, Bottom
// End - Revision Information, Bottom


// end of file - uexcptn.s
